import 'dart:collection';

enum PlaybackEventSource { streaming, downloaded, local, external, unknown }

/// A durable snapshot of one playback session.
///
/// [sessionId] is generated by the player when playback starts and remains
/// stable until that playback ends. Persisting the same session again updates
/// it instead of adding another play, which makes threshold and completion
/// writes idempotent.
class PlaybackEvent {
  PlaybackEvent({
    required this.sessionId,
    required this.trackId,
    required this.title,
    required List<String> artists,
    required this.source,
    required this.startedAt,
    required this.playedAt,
    required this.listenedMs,
    required this.completed,
    this.videoId,
    List<String?> artistBrowseIds = const <String?>[],
    this.album,
    this.thumbnailUrl,
    this.durationMs,
    this.isFavorite,
    this.isLiked,
  }) : artists = List<String>.unmodifiable(artists),
       artistBrowseIds = List<String?>.unmodifiable(artistBrowseIds);

  final String sessionId;
  final String trackId;
  final String? videoId;
  final String title;
  final List<String> artists;
  final List<String?> artistBrowseIds;
  final String? album;
  final String? thumbnailUrl;
  final int? durationMs;
  final PlaybackEventSource source;
  final DateTime startedAt;
  final DateTime playedAt;
  final int listenedMs;
  final bool completed;
  final bool? isFavorite;
  final bool? isLiked;

  /// YouTube identity is preferred; local-only tracks fall back to [trackId].
  String get trackKey =>
      recommendationTrackKey(videoId: videoId, trackId: trackId);
}

/// A distinct track aggregated from qualifying playback sessions.
class RecommendationSeed {
  RecommendationSeed({
    required this.trackKey,
    required this.trackId,
    required this.title,
    required List<String> artists,
    required this.source,
    required this.playCount,
    required this.totalListenedMs,
    required this.completedCount,
    required this.lastPlayedAt,
    this.videoId,
    List<String?> artistBrowseIds = const <String?>[],
    this.album,
    this.thumbnailUrl,
    this.durationMs,
    this.isFavorite,
    this.isLiked,
  }) : artists = List<String>.unmodifiable(artists),
       artistBrowseIds = List<String?>.unmodifiable(artistBrowseIds);

  final String trackKey;
  final String trackId;
  final String? videoId;
  final String title;
  final List<String> artists;
  final List<String?> artistBrowseIds;
  final String? album;
  final String? thumbnailUrl;
  final int? durationMs;
  final PlaybackEventSource source;
  final int playCount;
  final int totalListenedMs;
  final int completedCount;
  final DateTime lastPlayedAt;
  final bool? isFavorite;
  final bool? isLiked;

  bool get canQueryYouTube => videoId?.trim().isNotEmpty ?? false;
}

/// A YouTube candidate associated with one recommendation seed.
class RelatedTrackCandidate {
  RelatedTrackCandidate({
    required this.trackId,
    required this.title,
    required List<String> artists,
    required this.rank,
    this.videoId,
    List<String?> artistBrowseIds = const <String?>[],
    this.album,
    this.thumbnailUrl,
    this.durationMs,
    this.fetchedAt,
  }) : artists = List<String>.unmodifiable(artists),
       artistBrowseIds = List<String?>.unmodifiable(artistBrowseIds);

  final String trackId;
  final String? videoId;
  final String title;
  final List<String> artists;
  final List<String?> artistBrowseIds;
  final String? album;
  final String? thumbnailUrl;
  final int? durationMs;
  final int rank;

  /// Filled when read from storage. Callers may omit it when saving a batch.
  final DateTime? fetchedAt;

  String get trackKey =>
      recommendationTrackKey(videoId: videoId, trackId: trackId);
}

/// Serializable recommendation feed stored for instant startup rendering.
class RecommendationFeedCache {
  RecommendationFeedCache({
    required this.feedKey,
    required Map<String, Object?> payload,
    required this.generatedAt,
    required this.expiresAt,
  }) : payload = UnmodifiableMapView<String, Object?>(payload);

  final String feedKey;
  final Map<String, Object?> payload;
  final DateTime generatedAt;
  final DateTime expiresAt;

  bool isExpiredAt(DateTime now) => !expiresAt.isAfter(now);
}

String recommendationTrackKey({String? videoId, required String trackId}) {
  final normalizedVideoId = videoId?.trim();
  if (normalizedVideoId != null && normalizedVideoId.isNotEmpty) {
    return normalizedVideoId;
  }
  final normalizedTrackId = trackId.trim();
  if (normalizedTrackId.isEmpty) {
    throw ArgumentError.value(
      trackId,
      'trackId',
      'A trackId is required when videoId is absent.',
    );
  }
  return normalizedTrackId;
}
